version: "3.8"

services:
  uc-db:
    image: postgres:latest
    container_name: uc-db
    restart: on-failure
    env_file:
      - uc-app-back/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks: ["uc-backdb"]
    volumes:
      - uc-volume:/var/lib/postgresql

  uc-app-back:
    image: gabrielguidini/uc-app-back:latest
    container_name: uc-app-back
    restart: on-failure
    build:
      context: ./univille-calendar/uc-app-back
      dockerfile: uc-app-back/Dockerfile
    depends_on:
      - uc-db
    env_file:
      - uc-app-back/.env
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - uc-backdb
      - uc-backfront

  uc-app-front:
    image: gabrielguidini/uc-app-front:latest
    container_name: uc-app-front
    restart: on-failure
    build:
      context: ./univille-calendar/uc-app-front
      dockerfile: uc-app-back/Dockerfile
    depends_on:
      - uc-db
      - uc-app-back
    ports:
      - "3000:3000"
    networks: ["uc-backfront"]

networks:
  uc-backdb:
    driver: bridge
  uc-backfront:
    driver: bridge
volumes:
  uc-volume: {}