version: '3.8'

services:
  uc-db:
    image: postgres:latest
    container_name: uc-db
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks: ['uc-network']

  uc-app-back:
    image: gabrielguidini/uc-app-back:latest
    container_name: uc-app-back
    restart: on-failure
    build:
      context: ./univille-calendar/uc-app-back
      dockerfile: Dockerfile
    depends_on:
      - uc-db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks: ['uc-network']

  uc-app-front:
    image: gabrielguidini/uc-app-front:latest
    container_name: uc-app-front
    restart: always
    build:
      context: ./univille-calendar/uc-app-front
      dockerfile: Dockerfile
    depends_on:
      - uc-db
      - uc-app-back
    ports:
      - "3000:3000"
    networks: ['uc-network']

networks: {uc-network: {}}